// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Speed.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Speed_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Speed_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Speed_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Speed_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Speed_2eproto;
namespace foxglove {
class Speed;
struct SpeedDefaultTypeInternal;
extern SpeedDefaultTypeInternal _Speed_default_instance_;
}  // namespace foxglove
PROTOBUF_NAMESPACE_OPEN
template<> ::foxglove::Speed* Arena::CreateMaybeMessage<::foxglove::Speed>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace foxglove {

// ===================================================================

class Speed final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:foxglove.Speed) */ {
 public:
  inline Speed() : Speed(nullptr) {}
  ~Speed() override;
  explicit PROTOBUF_CONSTEXPR Speed(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Speed(const Speed& from);
  Speed(Speed&& from) noexcept
    : Speed() {
    *this = ::std::move(from);
  }

  inline Speed& operator=(const Speed& from) {
    CopyFrom(from);
    return *this;
  }
  inline Speed& operator=(Speed&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Speed& default_instance() {
    return *internal_default_instance();
  }
  static inline const Speed* internal_default_instance() {
    return reinterpret_cast<const Speed*>(
               &_Speed_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Speed& a, Speed& b) {
    a.Swap(&b);
  }
  inline void Swap(Speed* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Speed* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Speed* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Speed>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Speed& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Speed& from) {
    Speed::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Speed* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "foxglove.Speed";
  }
  protected:
  explicit Speed(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVXFieldNumber = 1,
    kVYFieldNumber = 2,
    kVRotateFieldNumber = 3,
  };
  // double v_x = 1;
  void clear_v_x();
  double v_x() const;
  void set_v_x(double value);
  private:
  double _internal_v_x() const;
  void _internal_set_v_x(double value);
  public:

  // double v_y = 2;
  void clear_v_y();
  double v_y() const;
  void set_v_y(double value);
  private:
  double _internal_v_y() const;
  void _internal_set_v_y(double value);
  public:

  // double v_rotate = 3;
  void clear_v_rotate();
  double v_rotate() const;
  void set_v_rotate(double value);
  private:
  double _internal_v_rotate() const;
  void _internal_set_v_rotate(double value);
  public:

  // @@protoc_insertion_point(class_scope:foxglove.Speed)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double v_x_;
    double v_y_;
    double v_rotate_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Speed_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Speed

// double v_x = 1;
inline void Speed::clear_v_x() {
  _impl_.v_x_ = 0;
}
inline double Speed::_internal_v_x() const {
  return _impl_.v_x_;
}
inline double Speed::v_x() const {
  // @@protoc_insertion_point(field_get:foxglove.Speed.v_x)
  return _internal_v_x();
}
inline void Speed::_internal_set_v_x(double value) {
  
  _impl_.v_x_ = value;
}
inline void Speed::set_v_x(double value) {
  _internal_set_v_x(value);
  // @@protoc_insertion_point(field_set:foxglove.Speed.v_x)
}

// double v_y = 2;
inline void Speed::clear_v_y() {
  _impl_.v_y_ = 0;
}
inline double Speed::_internal_v_y() const {
  return _impl_.v_y_;
}
inline double Speed::v_y() const {
  // @@protoc_insertion_point(field_get:foxglove.Speed.v_y)
  return _internal_v_y();
}
inline void Speed::_internal_set_v_y(double value) {
  
  _impl_.v_y_ = value;
}
inline void Speed::set_v_y(double value) {
  _internal_set_v_y(value);
  // @@protoc_insertion_point(field_set:foxglove.Speed.v_y)
}

// double v_rotate = 3;
inline void Speed::clear_v_rotate() {
  _impl_.v_rotate_ = 0;
}
inline double Speed::_internal_v_rotate() const {
  return _impl_.v_rotate_;
}
inline double Speed::v_rotate() const {
  // @@protoc_insertion_point(field_get:foxglove.Speed.v_rotate)
  return _internal_v_rotate();
}
inline void Speed::_internal_set_v_rotate(double value) {
  
  _impl_.v_rotate_ = value;
}
inline void Speed::set_v_rotate(double value) {
  _internal_set_v_rotate(value);
  // @@protoc_insertion_point(field_set:foxglove.Speed.v_rotate)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace foxglove

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Speed_2eproto
