// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ForkHeadSensorInFrame.proto

#include "ForkHeadSensorInFrame.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace foxglove {
PROTOBUF_CONSTEXPR ForkHeadSensorInFrame::ForkHeadSensorInFrame(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.distances_)*/{}
  , /*decltype(_impl_.frame_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.timestamp_)*/nullptr
  , /*decltype(_impl_.length_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ForkHeadSensorInFrameDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ForkHeadSensorInFrameDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ForkHeadSensorInFrameDefaultTypeInternal() {}
  union {
    ForkHeadSensorInFrame _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ForkHeadSensorInFrameDefaultTypeInternal _ForkHeadSensorInFrame_default_instance_;
}  // namespace foxglove
static ::_pb::Metadata file_level_metadata_ForkHeadSensorInFrame_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_ForkHeadSensorInFrame_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ForkHeadSensorInFrame_2eproto = nullptr;

const uint32_t TableStruct_ForkHeadSensorInFrame_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::foxglove::ForkHeadSensorInFrame, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::foxglove::ForkHeadSensorInFrame, _impl_.timestamp_),
  PROTOBUF_FIELD_OFFSET(::foxglove::ForkHeadSensorInFrame, _impl_.frame_id_),
  PROTOBUF_FIELD_OFFSET(::foxglove::ForkHeadSensorInFrame, _impl_.length_),
  PROTOBUF_FIELD_OFFSET(::foxglove::ForkHeadSensorInFrame, _impl_.distances_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::foxglove::ForkHeadSensorInFrame)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::foxglove::_ForkHeadSensorInFrame_default_instance_._instance,
};

const char descriptor_table_protodef_ForkHeadSensorInFrame_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\033ForkHeadSensorInFrame.proto\022\010foxglove\032"
  "\037google/protobuf/timestamp.proto\"{\n\025Fork"
  "HeadSensorInFrame\022-\n\ttimestamp\030\001 \001(\0132\032.g"
  "oogle.protobuf.Timestamp\022\020\n\010frame_id\030\002 \001"
  "(\t\022\016\n\006length\030\003 \001(\005\022\021\n\tdistances\030\004 \003(\001b\006p"
  "roto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_ForkHeadSensorInFrame_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::_pbi::once_flag descriptor_table_ForkHeadSensorInFrame_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ForkHeadSensorInFrame_2eproto = {
    false, false, 205, descriptor_table_protodef_ForkHeadSensorInFrame_2eproto,
    "ForkHeadSensorInFrame.proto",
    &descriptor_table_ForkHeadSensorInFrame_2eproto_once, descriptor_table_ForkHeadSensorInFrame_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_ForkHeadSensorInFrame_2eproto::offsets,
    file_level_metadata_ForkHeadSensorInFrame_2eproto, file_level_enum_descriptors_ForkHeadSensorInFrame_2eproto,
    file_level_service_descriptors_ForkHeadSensorInFrame_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ForkHeadSensorInFrame_2eproto_getter() {
  return &descriptor_table_ForkHeadSensorInFrame_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ForkHeadSensorInFrame_2eproto(&descriptor_table_ForkHeadSensorInFrame_2eproto);
namespace foxglove {

// ===================================================================

class ForkHeadSensorInFrame::_Internal {
 public:
  static const ::PROTOBUF_NAMESPACE_ID::Timestamp& timestamp(const ForkHeadSensorInFrame* msg);
};

const ::PROTOBUF_NAMESPACE_ID::Timestamp&
ForkHeadSensorInFrame::_Internal::timestamp(const ForkHeadSensorInFrame* msg) {
  return *msg->_impl_.timestamp_;
}
void ForkHeadSensorInFrame::clear_timestamp() {
  if (GetArenaForAllocation() == nullptr && _impl_.timestamp_ != nullptr) {
    delete _impl_.timestamp_;
  }
  _impl_.timestamp_ = nullptr;
}
ForkHeadSensorInFrame::ForkHeadSensorInFrame(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:foxglove.ForkHeadSensorInFrame)
}
ForkHeadSensorInFrame::ForkHeadSensorInFrame(const ForkHeadSensorInFrame& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ForkHeadSensorInFrame* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.distances_){from._impl_.distances_}
    , decltype(_impl_.frame_id_){}
    , decltype(_impl_.timestamp_){nullptr}
    , decltype(_impl_.length_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.frame_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.frame_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_frame_id().empty()) {
    _this->_impl_.frame_id_.Set(from._internal_frame_id(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_timestamp()) {
    _this->_impl_.timestamp_ = new ::PROTOBUF_NAMESPACE_ID::Timestamp(*from._impl_.timestamp_);
  }
  _this->_impl_.length_ = from._impl_.length_;
  // @@protoc_insertion_point(copy_constructor:foxglove.ForkHeadSensorInFrame)
}

inline void ForkHeadSensorInFrame::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.distances_){arena}
    , decltype(_impl_.frame_id_){}
    , decltype(_impl_.timestamp_){nullptr}
    , decltype(_impl_.length_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.frame_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.frame_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ForkHeadSensorInFrame::~ForkHeadSensorInFrame() {
  // @@protoc_insertion_point(destructor:foxglove.ForkHeadSensorInFrame)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ForkHeadSensorInFrame::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.distances_.~RepeatedField();
  _impl_.frame_id_.Destroy();
  if (this != internal_default_instance()) delete _impl_.timestamp_;
}

void ForkHeadSensorInFrame::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ForkHeadSensorInFrame::Clear() {
// @@protoc_insertion_point(message_clear_start:foxglove.ForkHeadSensorInFrame)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.distances_.Clear();
  _impl_.frame_id_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.timestamp_ != nullptr) {
    delete _impl_.timestamp_;
  }
  _impl_.timestamp_ = nullptr;
  _impl_.length_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ForkHeadSensorInFrame::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .google.protobuf.Timestamp timestamp = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_timestamp(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string frame_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_frame_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "foxglove.ForkHeadSensorInFrame.frame_id"));
        } else
          goto handle_unusual;
        continue;
      // int32 length = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.length_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated double distances = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_distances(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 33) {
          _internal_add_distances(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ForkHeadSensorInFrame::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:foxglove.ForkHeadSensorInFrame)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.protobuf.Timestamp timestamp = 1;
  if (this->_internal_has_timestamp()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::timestamp(this),
        _Internal::timestamp(this).GetCachedSize(), target, stream);
  }

  // string frame_id = 2;
  if (!this->_internal_frame_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_frame_id().data(), static_cast<int>(this->_internal_frame_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "foxglove.ForkHeadSensorInFrame.frame_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_frame_id(), target);
  }

  // int32 length = 3;
  if (this->_internal_length() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_length(), target);
  }

  // repeated double distances = 4;
  if (this->_internal_distances_size() > 0) {
    target = stream->WriteFixedPacked(4, _internal_distances(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:foxglove.ForkHeadSensorInFrame)
  return target;
}

size_t ForkHeadSensorInFrame::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:foxglove.ForkHeadSensorInFrame)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated double distances = 4;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_distances_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // string frame_id = 2;
  if (!this->_internal_frame_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_frame_id());
  }

  // .google.protobuf.Timestamp timestamp = 1;
  if (this->_internal_has_timestamp()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.timestamp_);
  }

  // int32 length = 3;
  if (this->_internal_length() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_length());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ForkHeadSensorInFrame::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ForkHeadSensorInFrame::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ForkHeadSensorInFrame::GetClassData() const { return &_class_data_; }


void ForkHeadSensorInFrame::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ForkHeadSensorInFrame*>(&to_msg);
  auto& from = static_cast<const ForkHeadSensorInFrame&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:foxglove.ForkHeadSensorInFrame)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.distances_.MergeFrom(from._impl_.distances_);
  if (!from._internal_frame_id().empty()) {
    _this->_internal_set_frame_id(from._internal_frame_id());
  }
  if (from._internal_has_timestamp()) {
    _this->_internal_mutable_timestamp()->::PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(
        from._internal_timestamp());
  }
  if (from._internal_length() != 0) {
    _this->_internal_set_length(from._internal_length());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ForkHeadSensorInFrame::CopyFrom(const ForkHeadSensorInFrame& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:foxglove.ForkHeadSensorInFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ForkHeadSensorInFrame::IsInitialized() const {
  return true;
}

void ForkHeadSensorInFrame::InternalSwap(ForkHeadSensorInFrame* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.distances_.InternalSwap(&other->_impl_.distances_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.frame_id_, lhs_arena,
      &other->_impl_.frame_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ForkHeadSensorInFrame, _impl_.length_)
      + sizeof(ForkHeadSensorInFrame::_impl_.length_)
      - PROTOBUF_FIELD_OFFSET(ForkHeadSensorInFrame, _impl_.timestamp_)>(
          reinterpret_cast<char*>(&_impl_.timestamp_),
          reinterpret_cast<char*>(&other->_impl_.timestamp_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ForkHeadSensorInFrame::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ForkHeadSensorInFrame_2eproto_getter, &descriptor_table_ForkHeadSensorInFrame_2eproto_once,
      file_level_metadata_ForkHeadSensorInFrame_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace foxglove
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::foxglove::ForkHeadSensorInFrame*
Arena::CreateMaybeMessage< ::foxglove::ForkHeadSensorInFrame >(Arena* arena) {
  return Arena::CreateMessageInternal< ::foxglove::ForkHeadSensorInFrame >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
