// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LinePrimitive.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Foxglove {

  /// <summary>Holder for reflection information generated from LinePrimitive.proto</summary>
  public static partial class LinePrimitiveReflection {

    #region Descriptor
    /// <summary>File descriptor for LinePrimitive.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LinePrimitiveReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNMaW5lUHJpbWl0aXZlLnByb3RvEghmb3hnbG92ZRoLQ29sb3IucHJvdG8a",
            "DFBvaW50My5wcm90bxoKUG9zZS5wcm90byKvAgoNTGluZVByaW1pdGl2ZRIq",
            "CgR0eXBlGAEgASgOMhwuZm94Z2xvdmUuTGluZVByaW1pdGl2ZS5UeXBlEhwK",
            "BHBvc2UYAiABKAsyDi5mb3hnbG92ZS5Qb3NlEhEKCXRoaWNrbmVzcxgDIAEo",
            "ARIXCg9zY2FsZV9pbnZhcmlhbnQYBCABKAgSIAoGcG9pbnRzGAUgAygLMhAu",
            "Zm94Z2xvdmUuUG9pbnQzEh4KBWNvbG9yGAYgASgLMg8uZm94Z2xvdmUuQ29s",
            "b3ISHwoGY29sb3JzGAcgAygLMg8uZm94Z2xvdmUuQ29sb3ISDwoHaW5kaWNl",
            "cxgIIAMoByI0CgRUeXBlEg4KCkxJTkVfU1RSSVAQABINCglMSU5FX0xPT1AQ",
            "ARINCglMSU5FX0xJU1QQAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Foxglove.ColorReflection.Descriptor, global::Foxglove.Point3Reflection.Descriptor, global::Foxglove.PoseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Foxglove.LinePrimitive), global::Foxglove.LinePrimitive.Parser, new[]{ "Type", "Pose", "Thickness", "ScaleInvariant", "Points", "Color", "Colors", "Indices" }, null, new[]{ typeof(global::Foxglove.LinePrimitive.Types.Type) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// A primitive representing a series of points connected by lines
  /// </summary>
  public sealed partial class LinePrimitive : pb::IMessage<LinePrimitive>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LinePrimitive> _parser = new pb::MessageParser<LinePrimitive>(() => new LinePrimitive());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LinePrimitive> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Foxglove.LinePrimitiveReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LinePrimitive() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LinePrimitive(LinePrimitive other) : this() {
      type_ = other.type_;
      pose_ = other.pose_ != null ? other.pose_.Clone() : null;
      thickness_ = other.thickness_;
      scaleInvariant_ = other.scaleInvariant_;
      points_ = other.points_.Clone();
      color_ = other.color_ != null ? other.color_.Clone() : null;
      colors_ = other.colors_.Clone();
      indices_ = other.indices_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LinePrimitive Clone() {
      return new LinePrimitive(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Foxglove.LinePrimitive.Types.Type type_ = global::Foxglove.LinePrimitive.Types.Type.LineStrip;
    /// <summary>
    /// Drawing primitive to use for lines
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Foxglove.LinePrimitive.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "pose" field.</summary>
    public const int PoseFieldNumber = 2;
    private global::Foxglove.Pose pose_;
    /// <summary>
    /// Origin of lines relative to reference frame
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Foxglove.Pose Pose {
      get { return pose_; }
      set {
        pose_ = value;
      }
    }

    /// <summary>Field number for the "thickness" field.</summary>
    public const int ThicknessFieldNumber = 3;
    private double thickness_;
    /// <summary>
    /// Line thickness
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Thickness {
      get { return thickness_; }
      set {
        thickness_ = value;
      }
    }

    /// <summary>Field number for the "scale_invariant" field.</summary>
    public const int ScaleInvariantFieldNumber = 4;
    private bool scaleInvariant_;
    /// <summary>
    /// Indicates whether `thickness` is a fixed size in screen pixels (true), or specified in world coordinates and scales with distance from the camera (false)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool ScaleInvariant {
      get { return scaleInvariant_; }
      set {
        scaleInvariant_ = value;
      }
    }

    /// <summary>Field number for the "points" field.</summary>
    public const int PointsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Foxglove.Point3> _repeated_points_codec
        = pb::FieldCodec.ForMessage(42, global::Foxglove.Point3.Parser);
    private readonly pbc::RepeatedField<global::Foxglove.Point3> points_ = new pbc::RepeatedField<global::Foxglove.Point3>();
    /// <summary>
    /// Points along the line
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Foxglove.Point3> Points {
      get { return points_; }
    }

    /// <summary>Field number for the "color" field.</summary>
    public const int ColorFieldNumber = 6;
    private global::Foxglove.Color color_;
    /// <summary>
    /// Solid color to use for the whole line. One of `color` or `colors` must be provided.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Foxglove.Color Color {
      get { return color_; }
      set {
        color_ = value;
      }
    }

    /// <summary>Field number for the "colors" field.</summary>
    public const int ColorsFieldNumber = 7;
    private static readonly pb::FieldCodec<global::Foxglove.Color> _repeated_colors_codec
        = pb::FieldCodec.ForMessage(58, global::Foxglove.Color.Parser);
    private readonly pbc::RepeatedField<global::Foxglove.Color> colors_ = new pbc::RepeatedField<global::Foxglove.Color>();
    /// <summary>
    /// Per-point colors (if specified, must have the same length as `points`). One of `color` or `colors` must be provided.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Foxglove.Color> Colors {
      get { return colors_; }
    }

    /// <summary>Field number for the "indices" field.</summary>
    public const int IndicesFieldNumber = 8;
    private static readonly pb::FieldCodec<uint> _repeated_indices_codec
        = pb::FieldCodec.ForFixed32(66);
    private readonly pbc::RepeatedField<uint> indices_ = new pbc::RepeatedField<uint>();
    /// <summary>
    /// Indices into the `points` and `colors` attribute arrays, which can be used to avoid duplicating attribute data.
    /// 
    /// If omitted or empty, indexing will not be used. This default behavior is equivalent to specifying [0, 1, ..., N-1] for the indices (where N is the number of `points` provided).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Indices {
      get { return indices_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LinePrimitive);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LinePrimitive other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(Pose, other.Pose)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Thickness, other.Thickness)) return false;
      if (ScaleInvariant != other.ScaleInvariant) return false;
      if(!points_.Equals(other.points_)) return false;
      if (!object.Equals(Color, other.Color)) return false;
      if(!colors_.Equals(other.colors_)) return false;
      if(!indices_.Equals(other.indices_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Foxglove.LinePrimitive.Types.Type.LineStrip) hash ^= Type.GetHashCode();
      if (pose_ != null) hash ^= Pose.GetHashCode();
      if (Thickness != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Thickness);
      if (ScaleInvariant != false) hash ^= ScaleInvariant.GetHashCode();
      hash ^= points_.GetHashCode();
      if (color_ != null) hash ^= Color.GetHashCode();
      hash ^= colors_.GetHashCode();
      hash ^= indices_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Foxglove.LinePrimitive.Types.Type.LineStrip) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (pose_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Pose);
      }
      if (Thickness != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Thickness);
      }
      if (ScaleInvariant != false) {
        output.WriteRawTag(32);
        output.WriteBool(ScaleInvariant);
      }
      points_.WriteTo(output, _repeated_points_codec);
      if (color_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Color);
      }
      colors_.WriteTo(output, _repeated_colors_codec);
      indices_.WriteTo(output, _repeated_indices_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Foxglove.LinePrimitive.Types.Type.LineStrip) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (pose_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Pose);
      }
      if (Thickness != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Thickness);
      }
      if (ScaleInvariant != false) {
        output.WriteRawTag(32);
        output.WriteBool(ScaleInvariant);
      }
      points_.WriteTo(ref output, _repeated_points_codec);
      if (color_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Color);
      }
      colors_.WriteTo(ref output, _repeated_colors_codec);
      indices_.WriteTo(ref output, _repeated_indices_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Foxglove.LinePrimitive.Types.Type.LineStrip) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (pose_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pose);
      }
      if (Thickness != 0D) {
        size += 1 + 8;
      }
      if (ScaleInvariant != false) {
        size += 1 + 1;
      }
      size += points_.CalculateSize(_repeated_points_codec);
      if (color_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Color);
      }
      size += colors_.CalculateSize(_repeated_colors_codec);
      size += indices_.CalculateSize(_repeated_indices_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LinePrimitive other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Foxglove.LinePrimitive.Types.Type.LineStrip) {
        Type = other.Type;
      }
      if (other.pose_ != null) {
        if (pose_ == null) {
          Pose = new global::Foxglove.Pose();
        }
        Pose.MergeFrom(other.Pose);
      }
      if (other.Thickness != 0D) {
        Thickness = other.Thickness;
      }
      if (other.ScaleInvariant != false) {
        ScaleInvariant = other.ScaleInvariant;
      }
      points_.Add(other.points_);
      if (other.color_ != null) {
        if (color_ == null) {
          Color = new global::Foxglove.Color();
        }
        Color.MergeFrom(other.Color);
      }
      colors_.Add(other.colors_);
      indices_.Add(other.indices_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Foxglove.LinePrimitive.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            if (pose_ == null) {
              Pose = new global::Foxglove.Pose();
            }
            input.ReadMessage(Pose);
            break;
          }
          case 25: {
            Thickness = input.ReadDouble();
            break;
          }
          case 32: {
            ScaleInvariant = input.ReadBool();
            break;
          }
          case 42: {
            points_.AddEntriesFrom(input, _repeated_points_codec);
            break;
          }
          case 50: {
            if (color_ == null) {
              Color = new global::Foxglove.Color();
            }
            input.ReadMessage(Color);
            break;
          }
          case 58: {
            colors_.AddEntriesFrom(input, _repeated_colors_codec);
            break;
          }
          case 66:
          case 69: {
            indices_.AddEntriesFrom(input, _repeated_indices_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Foxglove.LinePrimitive.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            if (pose_ == null) {
              Pose = new global::Foxglove.Pose();
            }
            input.ReadMessage(Pose);
            break;
          }
          case 25: {
            Thickness = input.ReadDouble();
            break;
          }
          case 32: {
            ScaleInvariant = input.ReadBool();
            break;
          }
          case 42: {
            points_.AddEntriesFrom(ref input, _repeated_points_codec);
            break;
          }
          case 50: {
            if (color_ == null) {
              Color = new global::Foxglove.Color();
            }
            input.ReadMessage(Color);
            break;
          }
          case 58: {
            colors_.AddEntriesFrom(ref input, _repeated_colors_codec);
            break;
          }
          case 66:
          case 69: {
            indices_.AddEntriesFrom(ref input, _repeated_indices_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the LinePrimitive message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// An enumeration indicating how input points should be interpreted to create lines
      /// </summary>
      public enum Type {
        /// <summary>
        /// 0-1, 1-2, ..., (n-1)-n
        /// </summary>
        [pbr::OriginalName("LINE_STRIP")] LineStrip = 0,
        /// <summary>
        /// 0-1, 1-2, ..., (n-1)-n, n-0
        /// </summary>
        [pbr::OriginalName("LINE_LOOP")] LineLoop = 1,
        /// <summary>
        /// 0-1, 2-3, 4-5, ...
        /// </summary>
        [pbr::OriginalName("LINE_LIST")] LineList = 2,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
