// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SteeringThetaInFrame.proto

#include "SteeringThetaInFrame.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace foxglove {
PROTOBUF_CONSTEXPR SteeringTheta::SteeringTheta(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.timestamp_)*/nullptr
  , /*decltype(_impl_.theta_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SteeringThetaDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SteeringThetaDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SteeringThetaDefaultTypeInternal() {}
  union {
    SteeringTheta _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SteeringThetaDefaultTypeInternal _SteeringTheta_default_instance_;
}  // namespace foxglove
static ::_pb::Metadata file_level_metadata_SteeringThetaInFrame_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_SteeringThetaInFrame_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_SteeringThetaInFrame_2eproto = nullptr;

const uint32_t TableStruct_SteeringThetaInFrame_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::foxglove::SteeringTheta, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::foxglove::SteeringTheta, _impl_.timestamp_),
  PROTOBUF_FIELD_OFFSET(::foxglove::SteeringTheta, _impl_.theta_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::foxglove::SteeringTheta)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::foxglove::_SteeringTheta_default_instance_._instance,
};

const char descriptor_table_protodef_SteeringThetaInFrame_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\032SteeringThetaInFrame.proto\022\010foxglove\032\037"
  "google/protobuf/timestamp.proto\"M\n\rSteer"
  "ingTheta\022-\n\ttimestamp\030\001 \001(\0132\032.google.pro"
  "tobuf.Timestamp\022\r\n\005theta\030\002 \001(\001b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_SteeringThetaInFrame_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::_pbi::once_flag descriptor_table_SteeringThetaInFrame_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_SteeringThetaInFrame_2eproto = {
    false, false, 158, descriptor_table_protodef_SteeringThetaInFrame_2eproto,
    "SteeringThetaInFrame.proto",
    &descriptor_table_SteeringThetaInFrame_2eproto_once, descriptor_table_SteeringThetaInFrame_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_SteeringThetaInFrame_2eproto::offsets,
    file_level_metadata_SteeringThetaInFrame_2eproto, file_level_enum_descriptors_SteeringThetaInFrame_2eproto,
    file_level_service_descriptors_SteeringThetaInFrame_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_SteeringThetaInFrame_2eproto_getter() {
  return &descriptor_table_SteeringThetaInFrame_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_SteeringThetaInFrame_2eproto(&descriptor_table_SteeringThetaInFrame_2eproto);
namespace foxglove {

// ===================================================================

class SteeringTheta::_Internal {
 public:
  static const ::PROTOBUF_NAMESPACE_ID::Timestamp& timestamp(const SteeringTheta* msg);
};

const ::PROTOBUF_NAMESPACE_ID::Timestamp&
SteeringTheta::_Internal::timestamp(const SteeringTheta* msg) {
  return *msg->_impl_.timestamp_;
}
void SteeringTheta::clear_timestamp() {
  if (GetArenaForAllocation() == nullptr && _impl_.timestamp_ != nullptr) {
    delete _impl_.timestamp_;
  }
  _impl_.timestamp_ = nullptr;
}
SteeringTheta::SteeringTheta(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:foxglove.SteeringTheta)
}
SteeringTheta::SteeringTheta(const SteeringTheta& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SteeringTheta* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.timestamp_){nullptr}
    , decltype(_impl_.theta_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_timestamp()) {
    _this->_impl_.timestamp_ = new ::PROTOBUF_NAMESPACE_ID::Timestamp(*from._impl_.timestamp_);
  }
  _this->_impl_.theta_ = from._impl_.theta_;
  // @@protoc_insertion_point(copy_constructor:foxglove.SteeringTheta)
}

inline void SteeringTheta::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.timestamp_){nullptr}
    , decltype(_impl_.theta_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SteeringTheta::~SteeringTheta() {
  // @@protoc_insertion_point(destructor:foxglove.SteeringTheta)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SteeringTheta::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.timestamp_;
}

void SteeringTheta::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SteeringTheta::Clear() {
// @@protoc_insertion_point(message_clear_start:foxglove.SteeringTheta)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.timestamp_ != nullptr) {
    delete _impl_.timestamp_;
  }
  _impl_.timestamp_ = nullptr;
  _impl_.theta_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SteeringTheta::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .google.protobuf.Timestamp timestamp = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_timestamp(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double theta = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _impl_.theta_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SteeringTheta::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:foxglove.SteeringTheta)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.protobuf.Timestamp timestamp = 1;
  if (this->_internal_has_timestamp()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::timestamp(this),
        _Internal::timestamp(this).GetCachedSize(), target, stream);
  }

  // double theta = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_theta = this->_internal_theta();
  uint64_t raw_theta;
  memcpy(&raw_theta, &tmp_theta, sizeof(tmp_theta));
  if (raw_theta != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_theta(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:foxglove.SteeringTheta)
  return target;
}

size_t SteeringTheta::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:foxglove.SteeringTheta)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .google.protobuf.Timestamp timestamp = 1;
  if (this->_internal_has_timestamp()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.timestamp_);
  }

  // double theta = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_theta = this->_internal_theta();
  uint64_t raw_theta;
  memcpy(&raw_theta, &tmp_theta, sizeof(tmp_theta));
  if (raw_theta != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SteeringTheta::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SteeringTheta::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SteeringTheta::GetClassData() const { return &_class_data_; }


void SteeringTheta::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SteeringTheta*>(&to_msg);
  auto& from = static_cast<const SteeringTheta&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:foxglove.SteeringTheta)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_timestamp()) {
    _this->_internal_mutable_timestamp()->::PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(
        from._internal_timestamp());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_theta = from._internal_theta();
  uint64_t raw_theta;
  memcpy(&raw_theta, &tmp_theta, sizeof(tmp_theta));
  if (raw_theta != 0) {
    _this->_internal_set_theta(from._internal_theta());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SteeringTheta::CopyFrom(const SteeringTheta& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:foxglove.SteeringTheta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SteeringTheta::IsInitialized() const {
  return true;
}

void SteeringTheta::InternalSwap(SteeringTheta* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SteeringTheta, _impl_.theta_)
      + sizeof(SteeringTheta::_impl_.theta_)
      - PROTOBUF_FIELD_OFFSET(SteeringTheta, _impl_.timestamp_)>(
          reinterpret_cast<char*>(&_impl_.timestamp_),
          reinterpret_cast<char*>(&other->_impl_.timestamp_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SteeringTheta::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_SteeringThetaInFrame_2eproto_getter, &descriptor_table_SteeringThetaInFrame_2eproto_once,
      file_level_metadata_SteeringThetaInFrame_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace foxglove
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::foxglove::SteeringTheta*
Arena::CreateMaybeMessage< ::foxglove::SteeringTheta >(Arena* arena) {
  return Arena::CreateMessageInternal< ::foxglove::SteeringTheta >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
